### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by sunthx** [CNU105/Retina-Unet#2]
执行 `python retinaNN_tranning.py` 报错

```bash
Traceback (most recent call last):
  File "retinaNN_training.py", line 100, in <module>
    visualize(group_images(patches_imgs_train[0:N_sample,:,:,:],5),'./'+name_experiment+'/'+"sample_input_imgs")#.show()
  File "C:\Users\user\Documents\repo\Retina-Unet\lib\help_functions.py", line 49, in visualize
    img.save(filename + '.png')
  File "C:\Users\user\unet\lib\site-packages\PIL\Image.py", line 2085, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './test/sample_input_imgs.png'
```

**Comment by GWwangshuo** [comment]
> 执行 `python retinaNN_tranning.py` 报错
> 
> ```shell
> Traceback (most recent call last):
>   File "retinaNN_training.py", line 100, in <module>
>     visualize(group_images(patches_imgs_train[0:N_sample,:,:,:],5),'./'+name_experiment+'/'+"sample_input_imgs")#.show()
>   File "C:\Users\user\Documents\repo\Retina-Unet\lib\help_functions.py", line 49, in visualize
>     img.save(filename + '.png')
>   File "C:\Users\user\unet\lib\site-packages\PIL\Image.py", line 2085, in save
>     fp = builtins.open(filename, "w+b")
> FileNotFoundError: [Errno 2] No such file or directory: './test/sample_input_imgs.png'
> ```

Just simply create a directory name 'test' will remove this error.

**Comment by gunflame530** [comment]
> > 执行 `python retinaNN_tranning.py` 报错
> > ```shell
> > Traceback (most recent call last):
> >   File "retinaNN_training.py", line 100, in <module>
> >     visualize(group_images(patches_imgs_train[0:N_sample,:,:,:],5),'./'+name_experiment+'/'+"sample_input_imgs")#.show()
> >   File "C:\Users\user\Documents\repo\Retina-Unet\lib\help_functions.py", line 49, in visualize
> >     img.save(filename + '.png')
> >   File "C:\Users\user\unet\lib\site-packages\PIL\Image.py", line 2085, in save
> >     fp = builtins.open(filename, "w+b")
> > FileNotFoundError: [Errno 2] No such file or directory: './test/sample_input_imgs.png'
> > ```
> 
> Just simply create a directory name 'test' will remove this error.

yes, it works
